name: Preprocessing Dataset

on:
  push:
    paths:
      - 'preprocessing/**'
      - 'Bank-Customer-Attrition-Insights-Data.csv'
      - '.github/workflows/preprocess.yml'
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas==2.2.2 scikit-learn==1.4.2 imbalanced-learn==0.12.2

      - name: Run Preprocessing Script
        run: python preprocessing/automate_nabilaalawiyah.py

      - name: Upload Preprocessed Dataset (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: dataset_preprocessing
          path: |
            preprocessing/dataset_preprocessing/
            bankdataset_preprocessed.csv

      - name: Commit processed dataset to repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add bankdataset_preprocessed.csv preprocessing/dataset_preprocessing/
          git commit -m "Update preprocessed dataset [skip ci]" || echo "No changes to commit"
          git push
